config/routes.rb
Rails.application.routes.draw do

  authenticate :user, ->(user) { user.admin? } do
    mount RailsAdmin::Engine, at: "admin", as: "rails_admin"
  end
  
  root "pages#home"

  resources :tasks

  resources :pomodoros do
    member do
      get :timer
    end
  end

  devise_for :users

  resources :pomodoro_tasks do
    member do
    patch :complete
    end
  end

end

app/models/pomodoro_task.rb
# == Schema Information
#
# Table name: pomodoro_tasks
#
#  id          :integer          not null, primary key
#  completed   :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  pomodoro_id :integer          not null
#  task_id     :integer          not null
#
# Indexes
#
#  index_pomodoro_tasks_on_pomodoro_id  (pomodoro_id)
#  index_pomodoro_tasks_on_task_id      (task_id)
#
# Foreign Keys
#
#  pomodoro_id  (pomodoro_id => pomodoros.id)
#  task_id      (task_id => tasks.id)
#
class PomodoroTask < ApplicationRecord
  belongs_to :pomodoro
  belongs_to :task

  after_destroy :destroy_orphaned_pomodoro
  
  private

  def destroy_orphaned_pomodoro
    pomodoro.destroy if pomodoro.tasks.empty?
  end

end

app/controllers/pomodoro_tasks_controller.rb
class PomodoroTasksController < ApplicationController
  before_action :set_pomodoro_task, only: %i[ show edit update destroy ]

  # GET /pomodoro_tasks or /pomodoro_tasks.json
  def index
    @pomodoro_tasks = PomodoroTask.joins(:pomodoro)
                                  .where(pomodoros: { user_id: current_user.id })
                                  .order(created_at: :desc)
  end

  # GET /pomodoro_tasks/1 or /pomodoro_tasks/1.json
  def show
  end

  # GET /pomodoro_tasks/new
  def new
    @pomodoro_task = PomodoroTask.new
  end

  # GET /pomodoro_tasks/1/edit
  def edit
  end

  # POST /pomodoro_tasks or /pomodoro_tasks.json
  def create
    @pomodoro_task = PomodoroTask.new(pomodoro_task_params)

    respond_to do |format|
      if @pomodoro_task.save
        format.html { redirect_to pomodoro_task_url(@pomodoro_task), notice: "Pomodoro task was successfully created." }
        format.json { render :show, status: :created, location: @pomodoro_task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pomodoro_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pomodoro_tasks/1 or /pomodoro_tasks/1.json
  def update
    respond_to do |format|
      if @pomodoro_task.update(pomodoro_task_params)
        format.html { redirect_to pomodoro_task_url(@pomodoro_task), notice: "Pomodoro task was successfully updated." }
        format.json { render :show, status: :ok, location: @pomodoro_task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pomodoro_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pomodoro_tasks/1 or /pomodoro_tasks/1.json
  def destroy
    @pomodoro_task.destroy

    respond_to do |format|
      format.html { redirect_to pomodoro_tasks_url, notice: "Pomodoro task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def complete
    @pomodoro_task = PomodoroTask.find_by(pomodoro_id: params[:id])
    @pomodoro_task.update(completed: true)
    head :ok
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pomodoro_task
      @pomodoro_task = PomodoroTask.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pomodoro_task_params
      params.require(:pomodoro_task).permit(:pomodoro_id, :task_id, :completed)
    end
end

app/views/pomodoro_tasks/_form.html.erb
<%= form_with(model: pomodoro_task) do |form| %>
  <% if pomodoro_task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pomodoro_task.errors.count, "error") %> prohibited this pomodoro_task from being saved:</h2>

      <ul>
        <% pomodoro_task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pomodoro_id, style: "display: block" %>
    <%= form.text_field :pomodoro_id %>
  </div>

  <div>
    <%= form.label :task_id, style: "display: block" %>
    <%= form.text_field :task_id %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pomodoro_tasks/_pomodoro_task.html.erb
<div id="<%= dom_id pomodoro_task %>">
  <p>
    <strong>Pomodoro:</strong>
    <%= pomodoro_task.pomodoro_id %>
  </p>

  <p>
    <strong>Task:</strong>
    <%= pomodoro_task.task_id %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= pomodoro_task.completed %>
  </p>

</div>

app/views/pomodoro_tasks/edit.html.erb
<h1>Editing pomodoro task</h1>

<%= render "form", pomodoro_task: @pomodoro_task %>

<br>

<div>
  <%= link_to "Show this pomodoro task", @pomodoro_task %> |
  <%= link_to "Back to pomodoro tasks", pomodoro_tasks_path %>
</div>

app/views/pomodoro_tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pomodoro tasks</h1>

<div id="pomodoro_tasks">
  <% @pomodoro_tasks.each do |pomodoro_task| %>
    <%= render pomodoro_task %>
    <p>
      <%= link_to "Show this pomodoro task", pomodoro_task %>
    </p>
  <% end %>
</div>

<%= link_to "New pomodoro task", new_pomodoro_task_path %>

app/views/pomodoro_tasks/new.html.erb
<h1>New pomodoro task</h1>

<%= render "form", pomodoro_task: @pomodoro_task %>

<br>

<div>
  <%= link_to "Back to pomodoro tasks", pomodoro_tasks_path %>
</div>

app/views/pomodoro_tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pomodoro_task %>

<div>
  <%= link_to "Edit this pomodoro task", edit_pomodoro_task_path(@pomodoro_task) %> |
  <%= link_to "Back to pomodoro tasks", pomodoro_tasks_path %>

  <%= button_to "Destroy this pomodoro task", @pomodoro_task, method: :delete %>
</div>