config/routes.rb
Rails.application.routes.draw do

  authenticate :user, ->(user) { user.admin? } do
    mount RailsAdmin::Engine, at: "admin", as: "rails_admin"
  end
  
  root "pages#home"

  resources :tasks

  resources :pomodoros do
    member do
      get :timer
    end
  end

  devise_for :users

  resources :pomodoro_tasks do
    member do
    patch :complete
    end
  end

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_tasks_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Task < ApplicationRecord
  belongs_to :user
  has_many :pomodoro_tasks, dependent: :destroy
  has_many :pomodoros, through: :pomodoro_tasks

  accepts_nested_attributes_for :pomodoro_tasks
  accepts_nested_attributes_for :pomodoros
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = current_user.tasks.order(created_at: :desc)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:user_id, :description, pomodoro_task_attributes: [:id, :pomodoro_id, :task_id, :completed, :_destroy])
    end
end

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="mb-3">
    <%= form.label :description, style: "display: block", for: "exampleFormControlTextarea1", class:"form-label" %>
    <%= form.text_area :description, class:"form-control", id:"exampleFormControlTextarea1" %>
  </div>

  <div>
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_social_share.html.erb
<% post_title = "I completed a task and I have earned #{current_user.pomodoro_tasks.where(completed: true).count} pomodoros" %>

<% post_url = request.original_url %>

<div class="share-btn-container">
  <%= link_to "https://www.facebook.com/sharer.php?u=#{post_url}", class: "facebook-btn", target: "_blank" do %>
    <i class="fab fa-facebook"></i>
  <% end %>

  <%= link_to "https://twitter.com/share?url=#{post_url}&text=#{post_title}", class: "twitter-btn", target: "_blank" do %>
    <i class="fab fa-twitter"></i>
  <% end %>

  <%= link_to "https://www.linkedin.com/shareArticle?url=#{post_url}&title=#{post_title}", class: "linkedin-btn", target: "_blank" do %>
    <i class="fab fa-linkedin"></i>
  <% end %>

  <%= link_to "mailto:?subject=#{post_title}&body=Check%20out%20this%20post:%20#{post_url}", class: "email-btn", target: "_blank" do %>
  <i class="fas fa-envelope"></i>
<% end %>
</div>

app/views/tasks/_task.html.erb
<tr id="<%= dom_id task %>" class="<%= cycle('table-primary', "") %>">
  <td>
    <%= task.description %>
  </td>
  <td class="text-left">
    <% task.pomodoro_tasks.where(completed: true).each do |_pomodoro| %>
      🍅
    <% end %>
  </td>
  <td>
    <div class="btn-group me-2" role="group" aria-label="Second group">
      <%= button_to "Edit", edit_task_path(task), method: :get, class: "btn btn-primary"%>
      <%= button_to "Delete", task, method: :delete, class: "btn btn-primary" %>
    </div>
  </td>
</tr>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<br>
<h1>To-Do List</h1>

<br>

<div>
  <%= render "form", task: Task.new %>
</div>

<br>

<div id="tasks">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Description</th>
      <th scope="col">Completed Pomodoros</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @tasks %>
  </tbody>
</table>
</div>

<%= render "social_share" %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>