config/routes.rb
Rails.application.routes.draw do

  authenticate :user, ->(user) { user.admin? } do
    mount RailsAdmin::Engine, at: "admin", as: "rails_admin"
  end
  
  root "pages#home"

  resources :tasks

  resources :pomodoros do
    member do
      get :timer
    end
  end

  devise_for :users

  resources :pomodoro_tasks do
    member do
    patch :complete
    end
  end

end

app/models/pomodoro.rb
# == Schema Information
#
# Table name: pomodoros
#
#  id         :integer          not null, primary key
#  break_time :integer
#  focus_time :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_pomodoros_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Pomodoro < ApplicationRecord
  belongs_to :user
  has_many :pomodoro_tasks, dependent: :destroy
  has_many :tasks, through: :pomodoro_tasks

  accepts_nested_attributes_for :pomodoro_tasks
  accepts_nested_attributes_for :tasks
end

app/controllers/pomodoros_controller.rb
class PomodorosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pomodoro, only: %i[ show edit update destroy ]

  # GET /pomodoros or /pomodoros.json
  def index
    if current_user
      @pomodoros = current_user.pomodoros
                               .joins(:pomodoro_tasks)
                               .where(pomodoro_tasks: { completed: false })
                               .order(created_at: :desc)
    end
  end

  # GET /pomodoros/1 or /pomodoros/1.json
  def show
  end

  # GET /pomodoros/new
  def new
    @pomodoro = Pomodoro.new(focus_time: 25, break_time: 5)
  end

  # GET /pomodoros/1/edit
  def edit
  end

  # POST /pomodoros or /pomodoros.json
  def create
    @pomodoro = current_user.pomodoros.build(pomodoro_params)

    respond_to do |format|
      if @pomodoro.save
        format.html { redirect_to pomodoros_path, notice: "Pomodoro was successfully created." }
        format.json { render :show, status: :created, location: @pomodoro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pomodoro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pomodoros/1 or /pomodoros/1.json
  def update
    respond_to do |format|
      if @pomodoro.update(pomodoro_params)
        format.html { redirect_to pomodoros_path, notice: "Pomodoro was successfully updated." }
        format.json { render :show, status: :ok, location: @pomodoro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pomodoro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pomodoros/1 or /pomodoros/1.json
  def destroy
    @pomodoro.destroy

    respond_to do |format|
      format.html { redirect_to pomodoros_url, notice: "Pomodoro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def timer
    @pomodoro = current_user.pomodoros.find(params[:id])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pomodoro
    @pomodoro = current_user.pomodoros.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pomodoro_params
    params.require(:pomodoro).permit(:focus_time, :break_time, pomodoro_tasks_attributes: [:id, :task_id, :completed, :_destroy, task_attributes: [:id, :description]])
  end
end

app/views/pomodoros/_form.html.erb
<%= form_with(model: pomodoro) do |form| %>
  <% if pomodoro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pomodoro.errors.count, "error") %> prohibited this pomodoro from being saved:</h2>
      <ul>
        <% pomodoro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.fields_for(:pomodoro_tasks, pomodoro.new_record? ? pomodoro.pomodoro_tasks.new : pomodoro.pomodoro_tasks) do |pomodoro_tasks_form| %>
      <%= form.label :task_id, "Task", class: "form-label mt-4", style: "display: block" %>
      <%= pomodoro_tasks_form.select :task_id, current_user.tasks.collect { |t| [t.description, t.id] }, { selected: current_user.tasks.order(created_at: :desc).first&.id, include_blank: false }, { class: "form-select", id: "exampleSelect1" } %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :focus_time, class: "form-label mt-4", style: "display: block" %>
    <%= form.number_field :focus_time, class: "form-control", placeholder: "Focus Time" %>
  </div>

  <div class="form-group">
    <%= form.label :break_time, class: "form-label mt-4", style: "display: block" %>
    <%= form.number_field :break_time, class: "form-control", placeholder: "Break Time" %>
  </div>
  <br>
  <div>
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/pomodoros/_p_form.html.erb
<%= form_with(model: pomodoro) do |form| %>
  <% if pomodoro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pomodoro.errors.count, "error") %> prohibited this pomodoro from being saved:</h2>

      <ul>
        <% pomodoro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% pomodoro.tasks.each do |task| %>
      <h5><%= task.description %></h5>
  <% end %>

<div class="form-group">
  <%= form.label :focus_time, class: "form-label mt-4", style: "display: block" %>
  <%= form.number_field :focus_time, class: "form-control", placeholder: "Focus Time" %>
</div>

<div class="form-group">
  <%= form.label :break_time, class: "form-label mt-4", style: "display: block" %>
  <%= form.number_field :break_time, class: "form-control", placeholder: "Break Time" %>
</div>

  <div>
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/pomodoros/_pomodoro.html.erb
<% pomodoro.tasks.each do |task| %>
  <tr id="<%= dom_id pomodoro %>" class="<%= cycle('table-primary', "") %>">
    <td><%= task.description %></td>
    <td><%= pomodoro.focus_time %></td>
    <td><%= pomodoro.break_time %></td>
    <td>
          <div class="btn-group me-2" role="group" aria-label="Second group">
      <%= button_to "Start", timer_pomodoro_path(pomodoro), method: :get, class: "btn btn-primary" %>
      <%= button_to "Edit", edit_pomodoro_path(pomodoro), method: :get, class: "btn btn-primary"%>
      <%= button_to "Delete", pomodoro, method: :delete, class: "btn btn-primary"%>
          </div>
    </td>
  </tr>
<% end %>

app/views/pomodoros/edit.html.erb
<h1>Editing Pomodoro</h1>
<br>
<%= render "p_form", pomodoro: @pomodoro %>

<br>

<div>
  <%= link_to "Back to pomodoros", pomodoros_path %>
</div>

app/views/pomodoros/index.html.erb
<br>
<h1>Pomodoros</h1>

<div>
  <%= render "form", pomodoro: Pomodoro.new(focus_time: 25, break_time: 5) %>
</div>

<br>

<div id="pomodoros">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Pomodoro</th>
        <th scope="col">Focus Time</th>
        <th scope="col">Break Time</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @pomodoros.each do |pomodoro| %>
        <%= render pomodoro %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pomodoros/new.html.erb
<h1>New pomodoro</h1>

<%= render "form", pomodoro: @pomodoro %>

<br>

<div>
  <%= link_to "Back to pomodoros", pomodoros_path %>
</div>

app/views/pomodoros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pomodoro %>

<div>
  <%= link_to "Edit this pomodoro", edit_pomodoro_path(@pomodoro) %> |
  <%= link_to "Back to pomodoros", pomodoros_path %>

  <%= button_to "Destroy this pomodoro", @pomodoro, method: :delete %>
</div>

app/views/pomodoros/timer.html.erb
<div class="center">
  <h1><div id="phase"></div></h1>
  <div id="message"></div>
  <h1><div id="timer" class="countdown-timer"></div></h1>
  <progress id="progress" max="1" value="1"></progress>
  <br>
  <div>
    <button id="pause/resume" class="btn btn-primary">Pause/Resume</button>
    <button id="reset" class="btn btn-primary">Reset</button>
  </div>
</div>

<script>
  var focusTime = <%= @pomodoro.focus_time * 60 %>;
  var breakTime = <%= @pomodoro.break_time * 60 %>;

  var countdown = focusTime;
  var isBreakTime = false;
  var isPaused = false;
  var startTime = Date.now();
  var timerId; 

  document.getElementById('phase').textContent = 'Focus Time';
  document.getElementById('progress').max = focusTime;

  function updateTimer() {
    if (!isPaused) {
      var elapsedTime = Math.floor((Date.now() - startTime) / 1000);
      countdown = isBreakTime ? breakTime - elapsedTime : focusTime - elapsedTime;
      if (countdown <= 0) {
        if (!isBreakTime) {
          countdown = focusTime;
          isBreakTime = true;
          startTime = Date.now();
          document.getElementById('phase').textContent = 'Break time';
          alert('Focus Time is up. Starting Break Time.');
          document.getElementById('progress').max = breakTime;
        } else {
          countdown = focusTime;
          isBreakTime = false;
          startTime = Date.now();
          document.getElementById('phase').textContent = 'Focus Time';
          alert('Break time is done.');
          clearInterval(timerId); 
          document.getElementById('phase').textContent = 'You Completed a Pomodoro!'; // Display the completion message

          
          fetch('<%= complete_pomodoro_task_path(@pomodoro.id) %>', {
            method: 'PATCH',
            headers: {
              'X-Requested-With': 'XMLHttpRequest',
              'Content-Type': 'application/json',
              'X-CSRF-Token': '<%= form_authenticity_token %>'
            },
            credentials: 'same-origin'
          });

          setTimeout(function() {
            var restart = confirm("Do you want to start another pomodoro?");
            if (restart) {
              
              countdown = focusTime;
              isBreakTime = false;
              startTime = Date.now();
              updateTimer(); 
              timerId = setInterval(updateTimer, 1000);
            } else {
              
              window.location.href = "/tasks"; 
            }
          }, 2000); 
        }
      }
      
      var hours = Math.floor(countdown / 3600);
      var minutes = Math.floor((countdown % 3600) / 60);
      var seconds = countdown % 60;
      document.getElementById('timer').textContent =
        (hours < 10 ? '0' : '') + hours + ':' +
        (minutes < 10 ? '0' : '') + minutes + ':' +
        (seconds < 10 ? '0' : '') + seconds;
      
      document.getElementById('progress').value = countdown;
    }
  }

  timerId = setInterval(updateTimer, 1000);

  document.getElementById('pause/resume').addEventListener('click', function() {
    isPaused = !isPaused;
    if (isPaused) {
      this.textContent = 'Resume';
    } else {
      this.textContent = 'Pause';
      if (isBreakTime) {
        startTime = Date.now() - (breakTime - countdown) * 1000;
      } else {
        startTime = Date.now() - (focusTime - countdown) * 1000;
      }
    }
  });

  document.getElementById('reset').addEventListener('click', function() {
    countdown = focusTime;
    isBreakTime = false;
    isPaused = false;
    startTime = Date.now();
    document.getElementById('phase').textContent = 'Focus Time';
    document.getElementById('progress').max = focusTime;
    document.getElementById('progress').value = countdown;
    document.getElementById('pause/resume').textContent = 'Pause';
  });
</script>