config/routes.rb
Rails.application.routes.draw do

  authenticate :user, ->(user) { user.admin? } do
    mount RailsAdmin::Engine, at: "admin", as: "rails_admin"
  end
  
  root "pages#home"

  resources :tasks

  resources :pomodoros do
    member do
      get :timer
    end
  end

  devise_for :users

  resources :pomodoro_tasks do
    member do
    patch :complete
    end
  end

end

app/views/shared/_cdn_assets.html.erb
<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.2/dist/united/bootstrap.min.css">

<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

<!-- Connect Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>

app/views/shared/_flash.html.erb
<% if notice.present? %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>

<% if alert.present? %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">

    <%= link_to "Pomodoro To-Do List Manager", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Home", tasks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Pomodoros", pomodoros_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto">
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
    </li>
  <% end %>
</ul>
    </div>
  </div>
</nav>